### ISSUE TITLE
[1.20.1] Incompatible with NeoForge due to Better Combat requiring Forge 47.2.0+

### ISSUE THREAD

**Issue by sentwayfarer** [Thelnfamous1/Better-Mob-Combat#1]
I tried using Better Combat 1.8,0 because that was the last version that worked with NeoForge on 1.20.1, and it seems this mod requires BC 1.8.5. The latest mod version on CurseForge says it's compatible with NeoForge, which is contradictory.
[latest.log](https://github.com/user-attachments/files/16120567/latest.log)

**Comment by Thelnfamous1** [comment]
Lowered minimum Better Combat version  to 1.7.3 per fd92075

**Comment by Thelnfamous1** [comment]
Fixed by version 1.1.0, now available on Curseforge (pending approval) and Modrinth. Thanks for reporting!
