### ISSUE TITLE
crash on 1.20.1

### ISSUE THREAD

**Issue by GauntAndreX8** [Thelnfamous1/Better-Mob-Combat#11]
[crash-2024-07-07_17.22.21-client.txt](https://github.com/user-attachments/files/16366324/crash-2024-07-07_17.22.21-client.txt)

**Comment by Thelnfamous1** [comment]
I don't even see Better Mob Combat mentioned anywhere in the crash report.

**Comment by GauntAndreX8** [comment]
oh sorry my bad
turns out it just gives an exit code -1 crash

**Comment by Thelnfamous1** [comment]
I can't diagnose the crash if the mod isn't even referred to in the report. You're positive this is the report you got when you attempted to launch with this mod?

**Comment by GauntAndreX8** [comment]
Yes

**Comment by Thelnfamous1** [comment]
Okay, the log is saying that a mod is trying to access Farmer Delight's Carrot Crate block before it is registered. Better Combat doesn't do that. The mod cited as trying to access the block seems to be Modern Fix. You need to bring this issue to them.

And again, I'm confused how this came from a modpack with Better Mob Combat in it if it's not at all listed in log's mod list.

**Comment by GauntAndreX8** [comment]
it turns out you forgot to put mob player animator as a requirement 
Figure that problem out

**Comment by GauntAndreX8** [comment]
Yeah sorry I forgot to add mob player animator mod
My bad
