### ISSUE TITLE
Two-handed weapons and food recruits

### ISSUE THREAD

**Issue by githuberbro** [Thelnfamous1/Better-Mob-Combat#12]
Another little issue apart from the shield one. When a villager recruit uses a two-handed weapon and also has a food in his inventory I noticed that the food disappears after some time, I think after he eats. Like the whole stack. Also when a recruit has a shield in the offhand and then I give him a two-handed weapon, the shield can completely disappear, but this is not as big as an issue as with the food. 

Overall this mod is awesome and it allows me to use villager recruits with mods like epic samurai and epic knights and makes the combat between recruits realistic, so I would like to say a huge thank you to the developer!

**Comment by 1092966399** [comment]
I also found this bug, villager recruits and better combat don't have this problem

**Comment by Thelnfamous1** [comment]
Will be fixed in version 1.2.2!

**Comment by Thelnfamous1** [comment]
Some things to keep in mind:

- Recruits will not show that they have a shield in their offhand, but they will still have it in their offhand when you open their inventory. This was always the case.
- Recruits will not attempt to eat food if they are holding a 2-handed weapon. This is consistent with players, who cannot eat food in their offhand while holding a 2-handed weapon. This will mean a recruit will never eat while it is equipped with a 2-handed weapon - something to keep in mind when you want to manage their hunger / health.
