### ISSUE TITLE
Vindicator Bug Animation

### ISSUE THREAD

**Issue by wabeb325** [Thelnfamous1/Better-Mob-Combat#16]
When a vindicator swings their axes, they hide their arms after the hit and a second later it turns back to normal.
( Tested the mod by standalone and without EMF)

Edit: This only happens to vindicators, with piglin brutes this doesn't happen. 

![2024-08-04_08 47 18](https://github.com/user-attachments/assets/666ddfa2-2db7-4ac7-a955-9e44ff88e714)

**Comment by Thelnfamous1** [comment]
This is already fixed for the upcoming 1.2.0 release.

**Comment by Thelnfamous1** [comment]
Duplicate of #15
