### ISSUE TITLE
Blacklist doesn't work

### ISSUE THREAD

**Issue by wabeb325** [Thelnfamous1/Better-Mob-Combat#17]
I tried to add some mobs into the blacklist and I tried two different format types just for verify, and even with that, the blacklist doesn't work, none of the mobs listed follows the blacklist.

(Using latest version)
![image](https://github.com/user-attachments/assets/672c8ff5-079d-4873-a190-9f5445c409dc)

**Comment by Thelnfamous1** [comment]
Can you explain a bit more how the blacklist is not working? Do you have the whitelist config enabled as well? Are the mobs still using Better Combat attacks/logic while they are blacklisted or are you trying to make them the only mobs able to use Better Combat attacks using the blacklist as a whitelist?

**Comment by wabeb325** [comment]
Well, first at all, the whitelist config ("mob_blacklist_as_whitelist") is not enable, and yeah, mobs still use Better Combat logic while they are blacklisted, that's the problem.

**Comment by Thelnfamous1** [comment]
Ok, and to be clear, you are not editing the config file mid-game? These configs cannot apply mid-game, only on restart

**Comment by wabeb325** [comment]
Yep, I'm editing them out of the game.

**Comment by Bem20** [comment]
it's happen me to 
![image](https://github.com/user-attachments/assets/59dc51fc-9669-4286-9f16-40b36cf5614f)

**Comment by BlackSapphier** [comment]
I have this issue too
![image](https://github.com/user-attachments/assets/b26da39d-2c63-4b77-8318-00a40e52b33d)

**Comment by Thelnfamous1** [comment]
@BlackSapphier From what I can tell, the maid doesn't have an attack AI.

**Comment by Thelnfamous1** [comment]
Can you all let me know which mobs specifically are not working? I know the maid is apparently one.

**Comment by Thelnfamous1** [comment]
Blacklist fix will be present in next release.
