### ISSUE TITLE
I noticed that the food in the backpack of the Villager Recruits with two-handed weapons was missing

### ISSUE THREAD

**Issue by 1092966399** [Thelnfamous1/Better-Mob-Combat#21]
Villager Recruits armed with two-handed weapons (such as Simply Swords-mod) will have all of their backpack food disappear when they need to regain their satiation

**Comment by Thelnfamous1** [comment]
Duplicate of #12

**Comment by Thelnfamous1** [comment]
Will be fixed in version 1.2.2!

**Comment by Thelnfamous1** [comment]
Some things to keep in mind:

- Recruits will not attempt to eat food if they are holding a 2-handed weapon. This is consistent with players, who cannot eat food in their offhand while holding a 2-handed weapon. This will mean a recruit will never eat while it is equipped with a 2-handed weapon - something to keep in mind when you want to manage their hunger / health.
