### ISSUE TITLE
Recruits Steve Models are glitched

### ISSUE THREAD

**Issue by Ldawsonm** [Thelnfamous1/Better-Mob-Combat#27]
The models are initially fine. However, after combat when it comes back to rest it rests in a weird position. Here the screenshots:

After killing a spider
![2024-09-13_17 35 08](https://github.com/user-attachments/assets/74d72d90-a2b9-49bc-81f7-2ddf543e5034)

A recruit that spawned in this position
![2024-09-13_17 58 48](https://github.com/user-attachments/assets/87a25c78-13cb-42de-8c31-7b9621b7ab6b)

The same recruit after I restarted my game
![2024-09-13_18 03 10](https://github.com/user-attachments/assets/693de9f1-4928-45f4-bce2-a6e92427728f)

**Comment by Thelnfamous1** [comment]
Update your Mob Player Animator version to 1.3.1. This issue was fixed for all mobs.

**Comment by Thelnfamous1** [comment]
See here: https://github.com/Thelnfamous1/Mob-Player-Animator/issues/9

**Comment by Ldawsonm** [comment]
Oh yeah that did it, thank you!
