### ISSUE TITLE
When was the fabric version released?

### ISSUE THREAD

**Issue by 970100646** [Thelnfamous1/Better-Mob-Combat#9]

**Comment by Thelnfamous1** [comment]
I haven't filled out the Fabric side of the Multiloader project yet. Another developer already contacted me about doing it themselves.

**Comment by 970100646** [comment]
> I haven't filled out the Fabric side of the Multiloader project yet. Another developer already contacted me about doing it themselves.

Will he publish it after he finishes writing it? I am very eager to have a fabric version

**Comment by Thelnfamous1** [comment]
It will be submitted to this repository and I will publish it.

**Comment by 970100646** [comment]
> 它将被提交到这个存储库并我会发布它。

thanks

**Comment by 970100646** [comment]
May I ask approximately when it can be completed

**Comment by 970100646** [comment]
> May I ask approximately when it can be completed

If I have offended you, I apologize first

**Comment by Thelnfamous1** [comment]
> May I ask approximately when it can be completed

Well, I was told by the developer that they would begin work prior to the 30th of August.

**Comment by 970100646** [comment]
> 谢谢

thanks

**Comment by 970100646** [comment]
Excuse me, may I ask if the development of the Fabric version has been completed

**Comment by Thelnfamous1** [comment]
The developer who was slated to work on it had to step away for personal reasons. I plan on developing and releasing the first Fabric version after I release a bug fix for the Forge version today.
